### ISSUE TITLE
TIPL not compiling

### ISSUE THREAD

**Issue by fissell** [frankyeh/TIPL#1]
Hi Frank,

The Nov 18 rev of TIPL is not compiling on Linux as part of DSI_Studio build.
Is it safe to take last week's DSI_Studio rev and last week's TIPL rev ?
How closely do I need to sync DSI_Studio and TIPL revs ?

thanks
Kate

```
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:233:10: error: ‘pixel_index’ was not declared in this scope
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:233:44: error: ‘iter’ was not declared in this scope
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:606:13: error: ‘pixel_index’ was not declared in this scope
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:606:40: error: ‘index’ does not have class type
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:606:69: error: ‘index’ does not have class type
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:607:25: error: ‘index’ does not have class type
../DSI-Studio_18Nov2013_Src/image/numerical/basic_op.hpp:607:43: error: ‘index’ does not have class type
../DSI-Studio_18Nov2013_Src/image/numerical/optimization.hpp:25:43: error: ‘class image::pixel_index<2u>’ has no member named ‘valid’
../DSI-Studio_18Nov2013_Src/image/numerical/dif.hpp:131:45: error: ‘class image::pixel_index<3u>’ has no member named ‘valid’
../DSI-Studio_18Nov2013_Src/image/numerical/dif.hpp:192:45: error: ‘class image::pixel_index<3u>’ has no member named ‘valid’
../DSI-Studio_18Nov2013_Src/image/numerical/dif.hpp:251:45: error: ‘class image::pixel_index<2u>’ has no member named ‘valid’
../DSI-Studio_18Nov2013_Src/image/numerical/dif.hpp:283:45: error: ‘class image::pixel_index<2u>’ has no member named ‘valid’
```

**Comment by frankyeh** [comment]
Hi Kate,

```
I would recommend you sync DSI Studio and TIPL at the same time. The
```

version from different time frame may not pass the compiler.

   The recent change I did to DSI Studio is only the syntax part. It does
not involve any computation update. Whether you use the last week rev and
current version should be consistent.

Best regards,
Frank

**Comment by fissell** [comment]
Thanks Frank !    Is the TIPL compile problem at my end or at your end ?   I cloned DSI-Studio and TIPL
this morning.

Kate

**Comment by frankyeh** [comment]
I will do the commit again to make sure that the codes are updated.

Best,
Frank

**Comment by fissell** [comment]
Hi,

I think I got your latest updates (Nov 19) but I am getting the same compile errors:
      basic_op.hpp:233:10: error: pixel_index was not declared in this scope  
and few more in basic_op.hpp
and I think optimization.hpp and  dif.hpp didn't get the pixel updates:
      optimization.hpp:25:43: error: class image::pixel_index has no member named valid

thanks
Kate

**Comment by frankyeh** [comment]
Hi Kate,

```
Thank for reporting these errors. I corrected them and uploaded the
```

update. It passed my compiler, and please compile it again to see if there
is any error at your side.

Best regards,
Frank

**Comment by fissell** [comment]
Thanks very much Frank !!!   It compiles now, we're testing !
