### ISSUE TITLE
problem with QValueAxis during compile

### ISSUE THREAD

**Issue by andregouws** [frankyeh/TIPL#10]
Debian stretch g++ 8 gcc 8

In both group_connectometry.cpp and nn_connectometry.cpp I get errors during compile when the attributes setTickType and setTickInterval are being set. e.g.

connectometry/group_connectometry.cpp: In member function ‘void group_connectometry::show_fdr_report()’:
connectometry/group_connectometry.cpp:169:60: error: ‘class QtCharts::QValueAxis’ has no member named ‘setTickType’; did you mean ‘setTickCount’?
     ((QValueAxis*)fdr_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                            ^~~~~~~~~~~
                                                            setTickCount
connectometry/group_connectometry.cpp:169:84: error: ‘TicksDynamic’ is not a member of ‘QtCharts::QValueAxis’
     ((QValueAxis*)fdr_chart->axes(Qt::Horizontal).back())->setTickType(QValueAxis::TicksDynamic);
                                                                                    ^~~~~~~~~~~~

.. which ulitmately results in:

`make: *** [Makefile:5051: group_connectometry.o] Error 1`

I have worked around this by simply commenting out any lines in group_connectometry.cpp and nn_connectometry.cpp that make calls to setTickType and setTickInterval. The package then compiles and runs, but obviously this is not ideal.

Thanks for your help.

Andre'

**Comment by frankyeh** [comment]
This code needs QtCharts to run, but some default packages do not have it.
Frank

**Comment by andregouws** [comment]
I was getting QtCharts errors earlier in the compile process but thought I had resolved those - I stopped getting errors after successfully running:

`sudo apt-get install libqt5charts5 libqt5charts5-dev `

**Comment by frankyeh** [comment]
Maybe the version is different?
' setTickType' needs QtCharts 5.13.2
Frank

**Comment by andregouws** [comment]
That'll be it - thanks Frank.

**Comment by andregouws** [comment]
For the record (and anyone else searching) - at this point in time Debian Stretch current libqt5charts5 and libqt5charts5-dev are at stable version 5.11.3 and 5.12 is only just in testing.

**Comment by frankyeh** [comment]
Thanks for the information, and sorry for the hassle!
Frank

**Comment by unimusic** [comment]
Sorry, how do we upgrade our version of qtcharts to the right one?

**Comment by frankyeh** [comment]
It is included in the  Qt. 5.12.2

**Comment by frankyeh** [comment]
I would suggest you use Docker or Singularity to run DSI Studio:
http://dsi-studio.labsolver.org/dsi-studio-download

**Comment by unimusic** [comment]
Sorry, I have Ubuntu 18.04. It looks like the Docker or Singularity options are for Mac. I'm not sure Qt above 5.9 is available for that in a stable release... is there a way to get around this? Sorry for the trouble!

**Comment by unimusic** [comment]
I'm attempting to install Qt 12 now. I'll update when it finishes, thanks!

**Comment by frankyeh** [comment]
https://docs.docker.com/engine/install/ubuntu/
https://singularity.lbl.gov/install-linux

**Comment by unimusic** [comment]
Oh, I didn't realize the container was cross platform. Singularity worked well. Thank you very much :)

**Comment by unimusic** [comment]
Hi Frank,

I am trying to visualize fibers, but get this error when running the module on singularity with Linux:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000', please create it with 0700 permissions.
process 26536: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize 0, samples 1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval -1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (8 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (8 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 8 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 8 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
qt.glx: qglx_findConfig: Failed to finding matching FBConfig (1 1 1 0)
Could not initialize GLX
Aborted (core dumped)
```
Please advise. Thank you!

**Comment by frankyeh** [comment]
It is a problem with Qt 5.12, and currently there seems no solution yet.
Frank

**Comment by unimusic** [comment]
I see. So there is not a way to visualize the fibers right now? Thanks!

**Comment by frankyeh** [comment]
It seems so. I am sorry about that.
Frank

**Comment by unimusic** [comment]
Okay I see. Thank you and please let me know if there's a solution.

**Comment by barbrakr** [comment]
Dear both,
Do you happen to know if there's a solution to this yet - I've seen a new QT version out - can that be used with dsistudio singularity?
Thanks,
Kind wishes,
Barbara

**Comment by frankyeh** [comment]
Singularity or docker container can now handle this problem.
We don't need to compile code to run DSI Studio on Linux systems.
Frank

**Comment by barbrakr** [comment]
oh, great, thanks!

**Comment by barbrakr** [comment]
Oh - actually, I just tried it out - it results in a Nov 3rd build and when loading a fib.gz file I get this in the Terminal (repeatedly)
GL_INVALID_OPERATION
begin

**Comment by frankyeh** [comment]
The error is caused by the openGL library.
There may be additional configuration needed to get a correct openGL with
singularity or docker container.
Frank

**Comment by andregouws** [comment]
> when loading a fib.gz file I get this in the Terminal (repeatedly)
> GL_INVALID_OPERATION
> begin

Same here with latest docker instance

**Comment by frankyeh** [comment]
I am sorry to hear this and wish I knew how to fix.

The same code works on Windows and Mac, but for some Linux systems
(not all Linux systems have this problem), the container does not work
with the OpenGL library. "GL_INVALID_OPERATION" is the error code when
openGL library failed to execute the function requested by DSI Studio.
Googling this error message with docker container or singularity leads
to a variety of possibilities. Some could be fixed at the OS level.

I will keep track of this issue and fix it if there is a solution.
Frank

**Comment by andregouws** [comment]
Don't be sorry!! You do sooo much hard work!! .. I'll keep debugging and
see what I can come up with...

**Comment by barbrakr** [comment]
Hi both,
Just found this repository that may do something for us... https://github.com/tashrifbillah/glxgears-containers - will check it out tomorrow!

**Comment by barbrakr** [comment]
Dear all, so we have tried something based on this: with cuda-drivers and the --nv flag
dsi_studio outputs this - not sure if this is some hint to some of you...
 dsi_studio: symbol lookup error: /.singularity.d/libs/libGL.so.1: undefined symbol: _glapi_tls_Current

**Comment by frankyeh** [comment]
googling the error message will lead to some solutions:
https://github.com/CoatiSoftware/Sourcetrail/issues/891

**Comment by andregouws** [comment]
So I got this working finally on Deb 10 (buster) - both on a personal
laptop and on my work PC.

Turns out there are a few authority/permissions challenges to expose the
display and opengl / other libraries to the docker session.

## ------------ code starts here

## CAREFUL - you may not want to remove any docker install you already have
- I just started from fresh
sudo apt-get remove docker docker-engine docker.io containerd runc
sudo apt-get update

# some core libs we'll need (may already be installed
sudo apt-get install     apt-transport-https     ca-certificates     curl
  gnupg-agent     software-properties-common

# this is Debian specific so may require alternatives in Ubuntu etc
sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key
add
sudo apt-key fingerprint 0EBFCD88
sudo add-apt-repository    "deb [arch=amd64]
https://download.docker.com/linux/debian \
                            (lsb_release -cs) \
                            stable"
sudo apt-get update

#  get docker
sudo apt-get install docker-ce docker-ce-cli containerd.io

#  set permissions (may already be set)
sudo groupadd docker
sudo usermod -aG docker $USER

# TEST that docker runs at least
docker run hello-world

# extra libs for dtistudio - you may or may not have these already
sudo apt-get install libxcb1-dev
sudo apt-get install libqt5opengl5
sudo apt-get install libqt5
sudo apt-get install libqt5charts5
sudo apt-get install libqt5core5a
sudo apt-get install libxcb1
sudo apt-get install xcb

# in case you need to check the xauth settings (debugging really)
xauth list

# --- READY TO GO - try one of the two options below

#sometimes we need this (usually on your personal laptop)
# NB replace the "/media/andre/disk/Common/dti/R1025" with the path to your
data folder (this is mounted as "data" in the docker instance file tree)

docker run  -it --network=host --env DISPLAY=$DISPLAY  --privileged
--volume="$HOME/.Xauthority:/root/.Xauthority:rw" -v
/tmp/.X11-unix:/tmp/.X11-unix  -v /media/andre/disk/Common/dti/R1025/:/data
--rm dsistudio/dsistudio:latest


# on my networked PC with extra safety / firewalls at work I have to run it
this way
# NB replace the "/var/tmp/" with the path to your data folder (this is
mounted as "data" in the docker instance file tree)

docker run  -it --network=host --env DISPLAY=$DISPLAY  --privileged -v
/tmp/.X11-unix:/tmp/.X11-unix  -v /var/tmp/:/data --rm
dsistudio/dsistudio:latest

### ----- code ends here

**Comment by frankyeh** [comment]
Thanks! This is really helpful!
Frank

**Comment by barbrakr** [comment]
okay, so for my situation the solution was to delete the /.singularity.d/libs from LD_LIBRARY_PATH , so instead I made these dependent on the libraries from my remote host system.

**Comment by humkies** [comment]
> okay, so for my situation the solution was to delete the /.singularity.d/libs from LD_LIBRARY_PATH , so instead I made these dependent on the libraries from my remote host system.

Hello,
I am having the same issue as you were having. I would really appreciate if you can give  more details on how you solved and error "GL_INVALID_OPERATION". 
Thanks
Joshi

**Comment by araikes** [comment]
@barbrakr I'd be curious how you accomplished this as well. I'm trying to do visualization on our HPC and get the GL_INVALID_OPERATION issue.

I can obviously do the visualization on my Windows machine, but I'm trying to keep everything contained to one location if I can.

**Comment by barbrakr** [comment]
IT solved it for me on our system (see below).

I guess there may be a different fix for other systems. The container will not run without these adjustments on our end (sorry some comments are still in German):

#Kurz zum Hintergrund: Der Container läuft nicht so richtig. Ich habe jetzt alle Bibliotheken vom SCC bzw. ugpu in den Container verlinkt. Dann geht es. Das heißt, man hat 4 Zeilen, die man auf der Kommandozeile ausführen muss. Ich kann dir das gerne nochmal in einer ViKo zeigen/erklären. Das ganze zum laufen zu kriege ist aber relativ einfach:
#Zuerst ganz normal die Konsole öffnen und

#go to some directory with fib-files
cd /usr/users/nmri/projects/kreilkamp/TueEpiMonogen_anon/dsistudio_singularity_output

module purge #make sure no other modules
module load singularity

#Dann ein

export LD_LIBRARY_PATH=/cm/local/apps/cuda-driver/libs/current/lib64:/cm/local/apps/gcc/8.2.0/lib64:/usr/lib64/VirtualGL:/lib64

#Dann mit einer shell den Container starten mit
singularity shell --bind /lib64/,/usr/lib64/,/cm/local/apps/cuda-driver/libs/current/lib64/,/cm/local/apps/gcc/8.2.0,/etc/machine-id $HOME/dsistudio_latest.sif

#Danach befindest du dich mit deiner bash im Container jetzt einmal
export XDG_RUNTIME_DIR=/usr/users/$USER

#Beim starten der Shell fügt Singularity das Verzeichnis
#/.singularity.d/libsdem LD_LIBRARY_PATH
#hinzu.
#Das wollen wir wieder rückgangig machen mit einem

export LD_LIBRARY_PATH=/cm/local/apps/cuda-driver/libs/current/lib64:/cm/local/apps/gcc/8.2.0/lib64:/usr/lib64/VirtualGL:/lib64

#go and start dsi_studio
#dsi_studio
