### ISSUE TITLE
Error when compile

### ISSUE THREAD

**Issue by Lincoln12w** [frankyeh/TIPL#5]
When compile the DSI-Studio on Linux, found some errors happen. Found that there are 3 BUGs in the source files:
1. utility/basic_image.hpp,  should include \<future\> & "pixel_index.hpp"
2. numerical/resampling.hpp:655, should add 'typename' before ImageType2::value_type
3. In repo DSI-Studio, regtoolbox.cpp:128, remove the '&' after 'auto', I'm not sure if it is mistyping or not.

By the way, The link to download the qt-everywhere-opensource  cannot use anymore, use http://download.qt.io/official_releases/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.tar.gz to get the newest version. And qt5-dev-tools can not found under ubuntu, I use qttools5-dev instead, not sure if they are same thing.

Thanks for sharing this software.

**Comment by Lincoln12w** [comment]
Also, when I run rec mode in command line with GQI method, It failed with "failed to locate template for QSDR reconstruction", while it is ok when I run this command with the mac pkg version. I found that in cmd/rec.cpp:101, the template is checked no matter what method is used. Wonder if it is a BUG, I just move the check into 'if(method_index == 7)'.
I'm not sure if it is necessary for the exist of template.

**Comment by frankyeh** [comment]
Thanks for the notice. I will update accordingly.

**Comment by frankyeh** [comment]
Please update the code and see if it works for you.

The template may be used if the user would like to output connectivity
matrix, which requires a spatial normalization.

Thank for reporting this problem.

Best regards,
Frank
