### ISSUE TITLE
Please make a versioned release

### ISSUE THREAD

**Issue by yarikoptic** [frankyeh/TIPL#7]
Ideally following the semantic versioning  https://semver.org .

**Comment by frankyeh** [comment]
Thank you for the suggestion.
I wish I could do a versioned release, but currently TIPL is mainly
developed for research purpose, and the update is continuous over time.
It is challenge to have a version control under limited manpower.
Sorry for the inconvenience.

Best regards,
Frank

**Comment by yarikoptic** [comment]
may be @frankyeh of DSI-Studio could help maintain ? ;)  my "greedy" desire here is to package DSI-Studio (and thus TIPL) for NeuroDebian as one of my collaborators wants to use it.  Having SOME releases/versioning would be better than me just coming up with 0.0.DATE "release"

**Comment by frankyeh** [comment]
Sure. @frankyeh <https://github.com/frankyeh> of DSI-Studio would love to
help :)

DSI Studio has very high turning rate as per feature request or bug fix
proposed by users (e.g. it was just updated today to fix a minor issue for
a user).

Currently we use "release date" as the version when communicating with
users.

Hope this is a possible workaround for you.

**Comment by yarikoptic** [comment]
FTR: I still don't see any tag or release being posted to https://github.com/frankyeh/TIPL/releases  so not sure why this issue was closed

**Comment by frankyeh** [comment]
Sorry for closing this issue.
The point in my last communication is that I cannot formally provide a
versioned releases due to frequent updates in DSI Studio and TIPL.
Instead, I usually communicate with users using the "date" of the TIPL
their downloaded.
I can re-open this issue again if needed.
Frank

**Comment by yarikoptic** [comment]
up to you -- it is your project(s). 
just know that your users (and outsiders like me) would only appreciate additional effort of the mighty `git tag` (at least) or pressing a button on releases pages

**Comment by frankyeh** [comment]
Thanks for the suggestion. I will try it out.
Best regards,
Frank

**Comment by frankyeh** [comment]
I created a 2019 November release and will create new releases
regularly in the future.
I did not know this function previously (sounds ridiculous...but true)
and thanks for the tip!
Best,
Frank
