### ISSUE TITLE
TIPL / DSI_studio compile error 

### ISSUE THREAD

**Issue by andregouws** [frankyeh/TIPL#9]
Hi - Thanks and congrats on a fantastic package!

I'm trying to compile on debian stretch - I cloned TIPL and DSI_studio this morning so have the latest code. I'm getting the following errors (e.g. march_cube.hpp:443:57: error: ‘class image_type::value_type’ resolves to ‘tipl::image<unsigned char, 3>::value_type’ {aka ‘unsigned char’}, which is is not a class type): 

Andre'

full error log:

In file included from ./tipl/tipl.hpp:85,
                 from tracking/region/RegionModel.h:7,
                 from tracking/region/RegionModel.cpp:6:
./tipl/vis/march_cube.hpp: In instantiation of ‘tipl::march_cube<VectorType>::march_cube(const ImageType&, double) [with ImageType = tipl::image<unsigned char, 3>; VectorType = tipl::vector<3>]’:
tracking/region/RegionModel.cpp:101:73:   required from here
./tipl/vis/march_cube.hpp:443:57: error: ‘class image_type::value_type’ resolves to ‘tipl::image<unsigned char, 3>::value_type’ {aka ‘unsigned char’}, which is is not a class type
             std::vector<typename ImageType::value_type> pixels;
                                                         ^~~~~~
./tipl/vis/march_cube.hpp:443:57: error: ‘class image_type::value_type’ resolves to ‘tipl::image<unsigned char, 3>::value_type’ {aka ‘unsigned char’}, which is is not a class type
In file included from ./tipl/numerical/basic_op.hpp:6,
                 from ./tipl/morphology/morphology.hpp:7,
                 from ./tipl/tipl.hpp:32,
                 from tracking/region/RegionModel.h:7,
                 from tracking/region/RegionModel.cpp:6:
./tipl/utility/multi_thread.hpp: In instantiation of ‘void tipl::par_for(T, Func, int) [with T = long unsigned int; Func = RegionModel::load(const std::vector<tipl::vector<3, short int> >&, double, unsigned char)::<lambda(unsigned int)>]’:
tracking/region/RegionModel.cpp:118:6:   required from here
./tipl/utility/multi_thread.hpp:25:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
     if(thread_count > size)
        ~~~~~~~~~~~~~^~~~~~
In file included from ./tipl/tipl.hpp:85,
                 from tracking/region/RegionModel.h:7,
                 from tracking/region/RegionModel.cpp:6:
./tipl/vis/march_cube.hpp: In instantiation of ‘tipl::march_cube<VectorType>::march_cube(const ImageType&, double) [with ImageType = tipl::image<float, 3>; VectorType = tipl::vector<3>]’:
tracking/region/RegionModel.cpp:154:27:   required from here
./tipl/vis/march_cube.hpp:443:57: error: ‘class image_type::value_type’ resolves to ‘tipl::image<float, 3>::value_type’ {aka ‘float’}, which is is not a class type
             std::vector<typename ImageType::value_type> pixels;
                                                         ^~~~~~
./tipl/vis/march_cube.hpp:443:57: error: ‘class image_type::value_type’ resolves to ‘tipl::image<float, 3>::value_type’ {aka ‘float’}, which is is not a class type
In file included from ./tipl/morphology/morphology.hpp:7,
                 from ./tipl/tipl.hpp:32,
                 from tracking/region/RegionModel.h:7,
                 from tracking/region/RegionModel.cpp:6:
./tipl/numerical/basic_op.hpp: In instantiation of ‘void tipl::change_endian(type&) [with type = double]’:
./tipl/numerical/basic_op.hpp:1043:22:   required from ‘void tipl::change_endian(datatype*, size_t) [with datatype = double; size_t = long unsigned int]’
./tipl/io/dicom.hpp:673:90:   required from here
./tipl/numerical/basic_op.hpp:1004:24: warning: comparison of integer expressions of different signedness: ‘char’ and ‘long unsigned int’ [-Wsign-compare]
     for (char i = 0; i < sizeof(type); ++i,--pdata)
                      ~~^~~~~~~~~~~~~~
./tipl/numerical/basic_op.hpp:1005:17: warning: array subscript has type ‘char’ [-Wchar-subscripts]
         temp[i] = *pdata;
In file included from ./tipl/numerical/basic_op.hpp:6,
                 from ./tipl/morphology/morphology.hpp:7,
                 from ./tipl/tipl.hpp:32,
                 from tracking/region/RegionModel.h:7,
                 from tracking/region/RegionModel.cpp:6:
./tipl/utility/multi_thread.hpp: In instantiation of ‘void tipl::par_for2(T, Func, unsigned int) [with T = long unsigned int; Func = tipl::bounding_box_mt(const std::vector<pixel_type>&, point_type&, point_type&) [with point_type = tipl::vector<3, short int>]::<lambda(unsigned int, unsigned int)>]’:
./tipl/numerical/basic_op.hpp:362:19:   required from ‘void tipl::bounding_box_mt(const std::vector<pixel_type>&, point_type&, point_type&) [with point_type = tipl::vector<3, short int>]’
tracking/region/RegionModel.cpp:63:52:   required from here
./tipl/utility/multi_thread.hpp:86:24: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
     for(int id = 1; id < thread_count; id++)
                     ~~~^~~~~~~~~~~~~~
In file included from ./tipl/tipl.hpp:41,
                 from tracking/region/RegionModel.h:7,
                 from tracking/region/RegionModel.cpp:6:
./tipl/numerical/resampling.hpp: In instantiation of ‘void tipl::downsampling(const ImageType1&, ImageType2&) [with ImageType1 = tipl::image<float, 3>; ImageType2 = tipl::image<float, 3>]’:
./tipl/numerical/resampling.hpp:611:17:   required from ‘void tipl::downsampling(ImageType&) [with ImageType = tipl::image<float, 3>]’
tracking/region/RegionModel.cpp:132:40:   required from here
./tipl/numerical/resampling.hpp:597:25: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
     for(int dim = 1;dim < ImageType1::dimension;++dim)
                     ~~~~^~~~~~~~~~~~
make: *** [Makefile:3145: RegionModel.o] Error 1

**Comment by andregouws** [comment]
Is this simply because I'm using a newer compiler? 

g++ --version
g++ (Debian 8.3.0-6) 8.3.0

gcc --version
gcc (Debian 8.3.0-6) 8.3.0

**Comment by frankyeh** [comment]
I am going to fix it.
Frank

**Comment by andregouws** [comment]
Thanks Frank for the record - I resolved that by simply changing:
`std::vector<typename ImageType::value_type> pixels;`
 to 
`std::vector<float> pixels;`
in march_cube.hpp

**Comment by frankyeh** [comment]
It seems that you are using an older version of TIPL. Could you verify?
Frank

**Comment by andregouws** [comment]
I did clone it this morning so I assume I have the latest? 

git clone https://github.com/frankyeh/TIPL.git

:/

**Comment by frankyeh** [comment]
The most update-to-date TIPL does not have ' class image_type::value_type'
in the march_cube.hpp
Frank

**Comment by andregouws** [comment]
https://github.com/frankyeh/TIPL/blob/master/vis/march_cube.hpp#L443

**Comment by frankyeh** [comment]
Line 443 has 'typename ImageType::value_type' but the error code shows
'class image_type:value_type'

**Comment by andregouws** [comment]
Not sure what to say further on this one - pretty sure I have the latest TIPL version (downloaded again) .. anyway, I have a workaround as described above: changing:
`std::vector<typename ImageType::value_type> pixels;`
to
`std::vector<float> pixels;`
That'll do me for now so feel free to close the issue.
Thanks
Andre'

**Comment by gdevenyi** [comment]
This bug still exists, and swapping `value_type` with `float` here:
https://github.com/frankyeh/TIPL/blob/master/vis/march_cube.hpp#L444

Allows building.
